### ISSUE TITLE
For the dataset

### ISSUE THREAD

**Issue by jiangchuanlu** [I-am-BigOrange/VigilanceNet#1]
Hello, I have constructed a SEED-VIG dataset with DE processing similar to your example data. However, during training and testing, the results are different from those obtained with your example data. I would like to consult with you regarding the details of dataset construction. For instance, how to partition training and testing for a single session, and whether there are any additional preprocessing steps for the data. Also, what is the best approach for handling EEG and EOG data? Thank you.

**Comment by I-am-BigOrange** [comment]
Thank you for your interest in our project!

During data preprocessing, the extracted EEG and EOG features were smoothed along the temporal dimension. Moreover, using linear dynamical system (LDS) can often obtain features that are easier to train than moving average. For SEED-VIG, we used “de_LDS” in EEG_Feature_5Bands and “features_table_icav_minh” in EOG_Feature for training and testing.

For a single session, 5-fold cross validation was used. The entire session was divided into 5 folds, each time 4 folds were used for training, and the rest one was for validation, and the predicted labels of the best epoch on the rest fold were recorded. Then concatenate the predicted labels of each fold according to the original order. The RMSE and CORR were calculated between the entire concatenated sequence and PERCLOS labels.
