### ISSUE TITLE
For the result

### ISSUE THREAD

**Issue by chyyyds** [I-am-BigOrange/VigilanceNet#2]
Hello,I have already applied for the SEED-VIG dataset and.According to your statement, use intra-session validation scheme to evaluate the model performance. 5-fold cross validation is used for this scheme.Then I averaged the COR and RMSE of each participant, but I couldn't get the 95% COR and 0.061 RMSE mentioned in your paper.May I ask if you have performed any other data preprocessing operations, or if I have set errors in reading files and 5-fold cross validation code

**Comment by I-am-BigOrange** [comment]
Thank you for your interest in our project!

During data preprocessing, the extracted EEG and EOG features were smoothed along the temporal dimension. Moreover, using linear dynamical system (LDS) can often obtain features that are easier to train than moving average. For SEED-VIG, we used “de_LDS” in EEG_Feature_5Bands and “features_table_icav_minh” in EOG_Feature for training and testing.

For a single session, 5-fold cross validation was used. The entire session was divided into 5 folds, each time 4 folds were used for training, and the rest one was for validation, and the predicted labels of the best epoch on the rest fold were recorded. Then concatenate the predicted labels of each fold according to the original order. The RMSE and CORR were calculated between the entire concatenated sequence and PERCLOS labels.

**Comment by chyyyds** [comment]
Thank you for your reply in my question!

Excuse me, do you mean that: for a session, there are a total of 885 samples. According to the five-fold cross-validation idea, that is, they are divided into [0,1,2,...,176],[177] in the original order. ,...,354],[354,...,531],[532,...,708],[709,...,884], and then select four  folds for training, leaving one to make predictions, these take a total of five training and five predictions.Finally, the results of each prediction are spliced in the original order, and then CORR and RMSE are calculated.

Is it then necessary to repeat the above operation for 23 subjects, obtain the CORR and RMSE of each of the 23 subjects, and then find the mean and standard deviation?

Please tell me if my understanding is correct. I would be grateful if you could reply!

**Comment by I-am-BigOrange** [comment]
That's right

**Comment by HaojiaYe** [comment]
Hello, I have learned that two kinds of data sets are used in this paper. One is SEED-VIG data set, and a single subject experiment is conducted. The other is the RSVP-VIG data set, and the comparison experiments between single subjects and cross-subjects are carried out respectively.

My current research direction is focused on multi-modal alertness detection across subjects, and I hope to make experimental comparison with relevant models and data sets. Since VigilanceNet does not have the SEED-VIG dataset to conduct cross-subject experiments, I wonder if we can apply for RSVP-VIG dataset? I would appreciate it if you could provide the RSVP-VIG data set! And in the future, if the relevant article is published, it will also mark the source of the data set!

Please kindly agree again. Thank you for your trouble!

This is my email address:   2110296053@email.szu.edu.cn

**Comment by HaojiaYe** [comment]
Hello, I have learned that two kinds of data sets are used in this paper. One is SEED-VIG data set, and a single subject experiment is conducted. The other is the RSVP-VIG data set, and the comparison experiments between single subjects and cross-subjects are carried out respectively.

My current research direction is focused on multi-modal alertness detection across subjects, and I hope to make experimental comparison with relevant models and data sets. Since VigilanceNet does not have the SEED-VIG dataset to conduct cross-subjects experiments, I wonder if we can apply for RSVP-VIG dataset? I would appreciate it if you could provide the RSVP-VIG data set! And in the future, if the relevant article is published, it will also mark the source of the data set!

Looking forward to your approval again! Thank you for your trouble!

This is my email address: 2110296053@email.szu.edu.cn

**Comment by Arong-gong** [comment]
Hi, I have some questions about the results. You pointed out in Table 4 of the article that the RMSE of LSTM-CapsAtt is 0.075 under the task of SEED-VIG. However, when I looked at the values reported by the original author [ref 1], there were some differences. The RMSE reported by the original author was 0.0295. Is there any subtle difference in the way the two papers are divided? 

[ref 1] G. Zhang and A. Etemad, "Capsule Attention for Multimodal EEG-EOG Representation Learning With Application to Driver Vigilance Estimation," in IEEE Transactions on Neural Systems and Rehabilitation Engineering, vol. 29, pp. 1138-1149, 2021, doi: 10.1109/TNSRE.2021.3089594.

I'm looking forward to hearing back from you.
![1](https://github.com/I-am-BigOrange/VigilanceNet/assets/41175098/f4f16699-57e8-47c6-ac88-b27ccfbb593b)
![2](https://github.com/I-am-BigOrange/VigilanceNet/assets/41175098/0e6b18a9-c43d-4d94-8bbf-bdfcff3494d7)

**Comment by I-am-BigOrange** [comment]
> Hello, I have learned that two kinds of data sets are used in this paper. One is SEED-VIG data set, and a single subject experiment is conducted. The other is the RSVP-VIG data set, and the comparison experiments between single subjects and cross-subjects are carried out respectively.
> 
> My current research direction is focused on multi-modal alertness detection across subjects, and I hope to make experimental comparison with relevant models and data sets. Since VigilanceNet does not have the SEED-VIG dataset to conduct cross-subjects experiments, I wonder if we can apply for RSVP-VIG dataset? I would appreciate it if you could provide the RSVP-VIG data set! And in the future, if the relevant article is published, it will also mark the source of the data set!
> 
> Looking forward to your approval again! Thank you for your trouble!
> 
> This is my email address: [2110296053@email.szu.edu.cn](mailto:2110296053@email.szu.edu.cn)

Currently, the process of open-sourcing our dataset is underway, and it will be released in the near future. We regret that we are unable to provide the dataset to you at this moment. If you are interested in our dataset, please stay tuned for the latest updates from our team.

**Comment by I-am-BigOrange** [comment]
> Hi, I have some questions about the results. You pointed out in Table 4 of the article that the RMSE of LSTM-CapsAtt is 0.075 under the task of SEED-VIG. However, when I looked at the values reported by the original author [ref 1], there were some differences. The RMSE reported by the original author was 0.0295. Is there any subtle difference in the way the two papers are divided?
> 
> [ref 1] G. Zhang and A. Etemad, "Capsule Attention for Multimodal EEG-EOG Representation Learning With Application to Driver Vigilance Estimation," in IEEE Transactions on Neural Systems and Rehabilitation Engineering, vol. 29, pp. 1138-1149, 2021, doi: 10.1109/TNSRE.2021.3089594.
> 
> I'm looking forward to hearing back from you. ![1](https://private-user-images.githubusercontent.com/41175098/288664697-f4f16699-57e8-47c6-ac88-b27ccfbb593b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjY2OTUsIm5iZiI6MTcwMjI2NjM5NSwicGF0aCI6Ii80MTE3NTA5OC8yODg2NjQ2OTctZjRmMTY2OTktNTdlOC00N2M2LWFjODgtYjI3Y2NmYmI1OTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAzNDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiY2RkMDY2ZWY2N2Y4NzllYTY0N2E2ZWM0YzdjMGZkYWExYmRjY2ExMmMxMGQwNDFiYzg0NDQ4MmZhYmE1NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.64iSZfubUzh5QcIH_QCpXhl2j6rkPHO6NMpvLMqFkik) ![2](https://private-user-images.githubusercontent.com/41175098/288664711-0e6b18a9-c43d-4d94-8bbf-bdfcff3494d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjY2OTUsIm5iZiI6MTcwMjI2NjM5NSwicGF0aCI6Ii80MTE3NTA5OC8yODg2NjQ3MTEtMGU2YjE4YTktYzQzZC00ZDk0LThiYmYtYmRmY2ZmMzQ5NGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAzNDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNTQwMjZiYWE3MDYxODY1NjVmOWM4ZDQ1ZjAyM2U0YTkzOTgzNzFkNzU0ODIxZDUwNWYzNTgxMTJiMjk5YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jJf6I9EyTI29e8s-xTxv52Ku-1hf4GlkQJgSCBJenlE)

In our paper, there is a slight difference in the dataset partitioning compared to [ref 1]. Our testing approach adheres to the dataset instructions provided by SEED-VIG. However, in [ref 1], before conducting 5-fold cross-validation, samples from a session are shuffled, and then the data is partitioned. In contrast, we did not shuffle data for dataset partitioning. This difference resulted in distinct experimental outcomes.

**Comment by Arong-gong** [comment]
Thank you for your patience and answering my questions. It is true that shuffle or not can seriously affect the performance of the model.

**Comment by HaojiaYe** [comment]
> Thank you for your interest in our project!感谢您对我们项目的关注！
> 
> During data preprocessing, the extracted EEG and EOG features were smoothed along the temporal dimension. Moreover, using linear dynamical system (LDS) can often obtain features that are easier to train than moving average. For SEED-VIG, we used “de_LDS” in EEG_Feature_5Bands and “features_table_icav_minh” in EOG_Feature for training and testing.在数据预处理过程中，提取的EEG和EOG特征沿时间维度进行平滑处理。此外，使用线性动力系统（LDS）通常可以获得比移动平均线更容易训练的特征。对于SEED-VIG，我们在EEG_Feature_5Bands中使用了“de_LDS”，在EOG_Feature中使用了“features_table_icav_minh”进行训练和测试。
> 
> For a single session, 5-fold cross validation was used. The entire session was divided into 5 folds, each time 4 folds were used for training, and the rest one was for validation, and the predicted labels of the best epoch on the rest fold were recorded. Then concatenate the predicted labels of each fold according to the original order. The RMSE and CORR were calculated between the entire concatenated sequence and PERCLOS labels.对于单个会话，使用了 5 倍交叉验证。整个会话分为 5 个折叠，每次 4 个折叠用于训练，其余一个用于验证，并记录其余折叠上最佳时期的预测标签。然后按照原来的顺序，将每个折叠的预测标签连接起来。在整个串联序列和PERCLOS标签之间计算RMSE和CORR。

Hi, following your data set selection method. I use "de_LDS" in EEG_Feature_5Bands and "features_table_icav_minh" in EOG_Feature. For a single session, the 5-fold cross-validation method is used and the best CORR is selected after 10 repetitions. The final CORR is the average of the best CORR of all sessions.

I followed the above ideas, and after many attempts, there were always a few sessions with  low CORR, affecting the average CORR of all sessions, and could not achieve such a good effect as 0.95 mentioned in the paper. May I ask if you choosed the average CORR of 23 sessions，or if I have set errors in code.
